name: Pipeline de Despliegue CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalando y probando
        run: |
          cd frontend
          cd react-app-productos
          npm install
          npm run build